require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - Guardfile
    - lib/**/*.erb
    - app/**/*.erb

Security/Open:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# It doesn't align when using `memoize def method_name`
Layout/RescueEnsureAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/BlockDelimiters:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/BracesAroundHashParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: true

Metrics/ParameterLists:
  Max: 6

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  CountComments: false
  Max: 160

Metrics/LineLength:
  Enabled: false
  Max: 140

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - spec/**/*

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/UnifiedInteger:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/BlockLength:
  Enabled: false

Naming/UncommunicativeBlockParamName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: true
  Severity: error

RSpec/AnyInstance:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 9

RSpec/MultipleSubjects:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/NotToNot:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: false

RSpec/SingleArgumentMessageChain:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
